name: analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Analyze package
        uses: axel-op/dart-package-analyzer@stable
        with:
          githubToken: ${{secrets.GITHUB_TOKEN}}
